"""add project model

Revision ID: 662d089c6692
Revises: 
Create Date: 2026-02-24 22:57:45.105059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662d089c6692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('repo_url', sa.String(length=256), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    # ### end Alembic commands ###
