"""add site settings

Revision ID: 75c3458d57d7
Revises: 662d089c6692
Create Date: 2026-02-24 23:14:36.277643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c3458d57d7'
down_revision = '662d089c6692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('github_url', sa.String(length=256), nullable=True),
    sa.Column('linkedin_url', sa.String(length=256), nullable=True),
    sa.Column('twitter_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
