"""add_project_sections

Revision ID: a04b4a959155
Revises: e9a1ff0affdb
Create Date: 2026-02-26 13:04:35.475897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04b4a959155'
down_revision = 'e9a1ff0affdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.String(length=128), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_sections_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_sections_project_id'))

    op.drop_table('project_sections')
    # ### end Alembic commands ###
