"""add project updated_at

Revision ID: e9a1ff0affdb
Revises: 75c3458d57d7
Create Date: 2026-02-24 23:37:55.751420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a1ff0affdb'
down_revision = '75c3458d57d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False,
                                       server_default=sa.text('CURRENT_TIMESTAMP')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
